---
# Creates a PostgreSQL role and database for the webmapp application, with relevant PostgreSQL extensions

- name: create a non-privileged postgresql role for webmap engine user
  postgresql_user:
    name="webmap"
    password="{{ app_database_user_password }}"
    state=present
  become_user: postgres

- name: create database for webmap engine application
  postgresql_db:
    name="webmap_engine"
    owner="webmap"
    state=present
  become_user: postgres

- name: set default database for webmap user
  lineinfile:
    dest='~/.bash_profile'
    line="export PGDATABASE=webmap_engine"
    create=yes
    state=present
  become_user: webmap

- name: enable postgresql extensions within webmap engine database
  postgresql_ext:
    name="{{ item }}"
    db="webmap_engine"
  with_items:
    - postgis
    - unaccent
    - fuzzystrmatch
  become_user: postgres
  
  # Set up web map specific schema and tables (added by David 11/05/2016)
  
- name: get SQL template
  template: 
    src=../../templates/database/webmap_schema.sql.j2
    dest="{{ app_unprivileged_home }}/webmap_schema.sql"
    owner=webmap
    mode=0664
    
- name: run SQL template
  shell: "psql -f {{ app_unprivileged_home }}/webmap_schema.sql webmap_engine"
  become_user: webmap
  
- name: delete SQL template
  file: path="{{ app_unprivileged_home }}/webmap_schema.sql" state=absent
  
  # End of David's changes
  
  
