---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensetive values are represented by "[Sensetive]"
#
# - Private key for the 'bas-magic-shared-deployment-identity'
# > SSH_PRIVATE_KEY: "[Sensetive]"

# == Global settings ==

stages:
  - build
  - distribute

variables:
  APP_NAME: bas-web-map-engine
  DEPLOY_HOST: bsl-repoa.nerc-bas.ac.uk

image:
  name: docker-registry.data.bas.ac.uk/magic/web-map-engine/web-map-engine-v1:latest
  entrypoint: [""]

# == Jobs ==

build-war:
  stage: build
  script:
    - "cp /usr/local/tomcat/webapps/ROOT.war ./web-map-engine.war"
  artifacts:
    name: "$CI_BUILD_TOKEN-build"
    paths:
      - web-map-engine.war
    expire_in: 1 week
  only:
    refs:
      - master
      - tags
    changes:
      - src

build-vm:
  stage: distribute
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_HOST > ~/.ssh/known_hosts
    - mv $SSH_PRIVATE_KEY ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - "cd provisioning/packer"
    - "/opt/packer validate web-map-engine-standalone.json"
    - "/opt/packer build web-map-engine-standalone.json"
    - "tree ."
  after_script:
    - pwd
    - ls ./
    - rm ~/.ssh/id_rsa
    - rm ~/.ssh/known_hosts
    - rmdir ~/.ssh
    - rm -f provisioning/packer/artefacts/ovas/web-map-engine-standalone-virtualbox/web-map-engine-standalone-*.ova
    - rm -f provisioning/packer/artefacts/vagrant-base-boxes/web-map-engine-standalone-virtualbox-*.box
    - rm -rf provisioning/packer/artefacts/ovas provisioning/packer/artefacts/vagrant-base-boxes provisioning/packer/artefacts
  cache:
    key: ${APP_NAME}-packer-cache
    paths:
      - provisioning/packer/packer_cache
  tags:
    - packer
    - virtualbox
