---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/magic/mapengine:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mdillon/postgis:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./src/main/webapp/WEB-INF/sql/table_creation/webmap_tables.sql:/docker-entrypoint-initdb.d/01-webmap-tables.sql"
    environment:
      - POSTGRES_PASSWORD=password
