---
version: '2'

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/magic/web-map-engine/web-map-engine-v1:latest
    volumes:
      - "./resources/:/usr/local/tomcat/mapengine-properties/"
    env_file:
      - .env
    depends_on:
      - db
      - geoserver
    ports:
      - "8080:8080"

  geoserver:
    image: docker-registry.data.bas.ac.uk/magic/infrastructure/docker-images/geoserver:latest
    volumes:
      - "./geoserver/data/:/var/geoserver/data/"
    environment:
      - "GEOSERVER_DATA_DIR=/var/geoserver/data"
    ports:
      - "8081:8080"

  db:
    image: mdillon/postgis:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./src/main/webapp/WEB-INF/sql/table_creation/webmap_tables.sql:/docker-entrypoint-initdb.d/10-webmap-tables.sql"
      - "./src/main/webapp/WEB-INF/sql/table_creation/webmap_auth_tables.sql:/docker-entrypoint-initdb.d/12-webmap-auth-tables.sql"
      - "./src/main/webapp/WEB-INF/sql/table_population/docker/test-data.sql:/docker-entrypoint-initdb.d/20-test-data.sql"
    environment:
      - POSTGRES_PASSWORD=password
