---
# Installs Java Advanced Imaging modules

- name: determine java path from java_home environment variable
  command: "echo $JAVA_HOME"
  changed_when: false
  register: app_geoserver_java_home

- name: check if java advanced imaging extension is installed
  stat: path="{{ app_geoserver_java_home.stdout }}/UNINSTALL-jai"
  register: app_geoserver_fact_jai_installed

- name: check if java advanced imaging I/O extension is installed
  stat: path="{{ app_geoserver_java_home.stdout }}/UNINSTALL-jai_imageio"
  register: app_geoserver_fact_jai_io_installed

- name: download java advanced imaging extension installer
  get_url:
     url="http://download.java.net/media/jai/builds/release/{{ app_geoserver_native_jai_major_version }}_{{ app_geoserver_native_jai_minor_version }}_{{ app_geoserver_native_jai_patch_version }}/jai-{{ app_geoserver_native_jai_major_version }}_{{ app_geoserver_native_jai_minor_version }}_{{ app_geoserver_native_jai_patch_version }}-lib-linux-amd64-jre.bin"
    dest="{{ app_geoserver_java_home.stdout }}/jai_extension.bin"
    mode=755
  when: app_geoserver_fact_jai_installed.stat.exists is defined and app_geoserver_fact_jai_installed.stat.exists == false

- name: download java advanced imaging I/O extension installer
  get_url:
     url="http://download.java.net/media/jai-imageio/builds/release/{{ app_geoserver_native_jai_imageio_major_version }}.{{ app_geoserver_native_jai_imageio_minor_version }}/jai_imageio-{{ app_geoserver_native_jai_imageio_major_version }}_{{ app_geoserver_native_jai_imageio_minor_version }}-lib-linux-amd64-jre.bin"
    dest="{{ app_geoserver_java_home.stdout }}/jai_io_extension.bin"
    mode=755
  when: app_geoserver_fact_jai_io_installed.stat.exists is defined and app_geoserver_fact_jai_io_installed.stat.exists == false

- name: install java advanced imaging extension
  shell: "bash ./jai_extension.bin < <(echo y) < <(echo y) chdir={{ app_geoserver_java_home.stdout }} executable=/bin/bash"
  notify:
    - Restart Tomcat
  ignore_errors: true
  when: app_geoserver_fact_jai_installed.stat.exists is defined and app_geoserver_fact_jai_installed.stat.exists == false

- name: install java advanced imaging I/O extension
  shell: "bash ./jai_io_extension.bin < <(echo y) < <(echo y) chdir={{ app_geoserver_java_home.stdout }} executable=/bin/bash"
  environment:
    _POSIX2_VERSION: 199209
  notify:
    - Restart Tomcat
  when: app_geoserver_fact_jai_io_installed.stat.exists is defined and app_geoserver_fact_jai_io_installed.stat.exists == false

- name: remove java advanced imaging extension installer
  file:
     path="{{ app_geoserver_java_home.stdout }}/jai_extension.bin"
    state=absent
  when: app_geoserver_fact_jai_installed.stat.exists is defined and app_geoserver_fact_jai_installed.stat.exists == false

- name: remove java advanced imaging I/O extension installer
  file:
     path="{{ app_geoserver_java_home.stdout }}/jai_io_extension.bin"
    state=absent
  when: app_geoserver_fact_jai_io_installed.stat.exists is defined and app_geoserver_fact_jai_io_installed.stat.exists == false
