---
# Removes the root, documentation and examples default tomcat applications

- name: check which tomcat applications are deployed
  uri:
              user="{{ app_tomcat_admin_user_username }}"
          password="{{ app_tomcat_admin_user_password }}"
               url="http://{{ app_tomcat_listening_address }}:{{ app_tomcat_listening_port }}/manager/text/list"
    return_content=yes
  register: app_tomcat8_fact_applications_list

- name: undeploy default tomcat applications
  uri:
              user="{{ app_tomcat_admin_user_username }}"
          password="{{ app_tomcat_admin_user_password }}"
               url="http://{{ app_tomcat_listening_address }}:{{ app_tomcat_listening_port }}/manager/text/undeploy?path={{ item.path }}"
    return_content=yes
  changed_when: true
  with_items: app_tomcat_undeployed_applications
  when: true == true and '{{ item.context }}' in "{{ app_tomcat8_fact_applications_list.content }}"

- name: check which tomcat applications are deployed
  uri:
              user="{{ app_tomcat_admin_user_username }}"
          password="{{ app_tomcat_admin_user_password }}"
               url="http://{{ app_tomcat_listening_address }}:{{ app_tomcat_listening_port }}/manager/text/list"
    return_content=yes
  register: app_tomcat8_fact_applications_list

- name: assert any applications to be undeployed are undeployed
  assert:
    that:
      - "'{{ item.context }}' not in app_tomcat8_fact_applications_list.content"
  with_items: app_tomcat_undeployed_applications
