---

# Add extra configuration in bin/setenv.sh - added by David 12/05/2016

- name: generate setenv.sh configuration file
  template:
     src=../../templates/opt/tomcat8/bin/setenv.sh.j2
     dest=/opt/tomcat8/bin/setenv.sh
    owner=tomcat
    group=adm
    
# Configure server port and compression targets in server.xml
- name: generate server.xml configuration file
  template:
     src=../../templates/etc/tomcat8/conf/server.xml.j2
     dest=/etc/tomcat8/conf/server.xml
    owner=tomcat
    group=adm

# End of David's additions

# Configures the tomcat manager application for deploying WAR files

- name: generate tomcat-users configuration file
  template:
      src=../../templates/etc/tomcat8/conf/tomcat-users.xml.j2
     dest=/etc/tomcat8/conf/tomcat-users.xml
    owner=tomcat
    group=adm
  notify: Restart Tomcat
  register: app_tomcat_users_updated

# Tomcat needs to be restarted to use updated user file
# Tomcat doesn't restart that quickly so we need to wait a bit before trying to hit its API,
# otherwise we get a refused connection :/
- meta: flush_handlers
- wait_for:
    port="{{ tomcat8_firewall_port_http }}"
    delay=10
  when: app_tomcat_users_updated.changed is defined and app_tomcat_users_updated.changed == true
