---
# Setup infrastructure and application for development environment

- name: setup development nodes
  hosts: project--webmap-engine:&env--dev-local
  remote_user: "{{ privileged_remote_user }}"
  become: yes
  roles:
    - bas-ansible-roles-collection.system-core
    - bas-ansible-roles-collection.postgresql9-ext-postgis
    - bas-ansible-roles-collection.tomcat8
  tasks:
<<<<<<< fb46edc3eaade61bed87b7ba73f3e2d134b49077
    - include: tasks/ansible/setup-ansible-uri-module.yml
    - include: tasks/ansible/setup-ansible-unarchive-module.yml

    - include: tasks/oracle-jdk7/install-java-advanced-imaging.yml

    - include: tasks/database/setup-webmap-database.yml
    - include: tasks/tomcat/setup-tomcat-manager.yml
    - include: tasks/tomcat/remove-default-applications.yml

    - include: tasks/geoserver/deploy-geoserver.yml
    - include: tasks/geoserver/configure-geoserver.yml
=======
    - name: create a non-privileged postgresql role for webmap engine user
      postgresql_user:
        name="webmap"
        password="password"
        state=present
      become_user: postgres
    - name: create database for webmap engine application
      postgresql_db:
        name="webmap_engine"
        owner="webmap"
        state=present
      become_user: postgres
    - name: enable postgresql extensions within webmap engine database
      postgresql_ext:
        name="{{ item }}"
        db="webmap_engine"
      with_items:
        - postgis
        - unaccent
        - fuzzystrmatch
      become_user: postgres
    - name: set default database for webmap user
      lineinfile:
        dest='~/.bash_profile'
        line="export PGDATABASE=webmap_engine"
        state=present
      become_user: webmap
    - include: tasks/tomcat/setup-tomcat-manager.yml
>>>>>>> Adding java and tomcat basic support
  handlers:
    - include: roles/bas-ansible-roles-collection.tomcat8/handlers/main.yml
