---
# Setup infrastructure and application for production environment

- name: setup production nodes
  hosts: project--webmap-engine:&env--prod
  remote_user: "{{ privileged_remote_user }}"
  become: yes
  pre_tasks: 
    - name: cleanup-postgres
      file: path=/var/lib/pgsql/9.5/data//pg_log state=absent
  roles:
    - bas-ansible-roles-collection.system-core
    - bas-ansible-roles-collection.postgresql9-ext-postgis
    - bas-ansible-roles-collection.tomcat8
  tasks:
    - include: tasks/ansible/setup-ansible-uri-module.yml
    - include: tasks/ansible/setup-ansible-unarchive-module.yml

    - include: tasks/oracle-jdk7/install-java-advanced-imaging.yml

    - include: tasks/database/setup-webmap-database.yml
    - include: tasks/tomcat/setup-tomcat-manager.yml
    - include: tasks/tomcat/remove-default-applications.yml

    - include: tasks/geoserver/deploy-geoserver.yml
    - include: tasks/geoserver/configure-geoserver.yml
    
    - include: tasks/app/deploy-webmap-engine.yml
  handlers:
    - include: roles/bas-ansible-roles-collection.tomcat8/handlers/main.yml
