---
# These variables override those defined by roles

# App variables - apply to a single project
app_project: "webmap-engine"
app_project_repository: "ssh://git@stash.ceh.ac.uk:7999/magic/webmap_engine.git"
app_project_directory: "/srv/apps/{{ app_project }}"

app_database_user_password: password

app_tomcat_admin_user_username: admin
app_tomcat_admin_user_password: password

app_tomcat_listening_address: "{{ ansible_fqdn }}"
app_tomcat_listening_port: "{{ tomcat8_firewall_port_http }}"

app_tomcat_undeployed_applications:
  -
    path: "/"
    context: "/:running:0:ROOT"
  -
    path: "/docs"
    context: "/docs:running:0:docs"
  -
    path: "/examples"
    context: "/examples:running:0:examples"

# system-users specific variables
system_users_users:
  -
    username: webmap
    comment: Generic unprivileged account for performing day-to-day webmap-engine application related tasks
    shell: /bin/bash
    authorized_keys_directory: files/HOME/DOT-ssh/authorized-keys
    authorized_keys_files:
      - "darb1.pub"
      - "dacon.pub"
      - "felnne.pub"
      - "jpro.pub"
    state: present
  -
    username: admin
    comment: TEMPORARY Generic privileged account for performing administration or diagnostic webmap-engine application related tasks
    shell: /bin/bash
    authorized_keys_directory: files/HOME/DOT-ssh/authorized-keys
    authorized_keys_files:
      - "darb1.pub"
      - "dacon.pub"
      - "felnne.pub"
      - "jpro.pub"
    secondary_groups:
      - adm
    sudo: true
    state: present
